### ISSUE TITLE
Allow support of custom CSS

### ISSUE THREAD

**Issue by Lagicrus** [portsoc/chator#7]
See title

**Comment by ear1grey** [comment]
How do you envision this working?

**Comment by Hopson97** [comment]
JavaScript could be used to generate the HTML for loading a CSS file. 

A user could use something like https://fineuploader.com/ to upload a CSS file, and then the page could be reloaded (can this be done in JS?). 

Maybe Web Storage could be used to see the last CSS file uploaded after the page is reloaded, which the JS to generate the HTML for loading the CSS file could use.

Something like this (untested):

```js
function web_storage_supported() {
    return typeof(Storage) !== "undefined";
}

function load_css_from_storage(element) {

    let path_to_custom_css = window.localStorage.getItem("custom_css");
    if (path_to_custom_css === null) {
        load_default_css(element);
    } else {
        validator.insertAdjacentHTML("afterbegin", 
        `
            <link rel="stylesheet" type="text/css" href="${path_to_custom_css}">
        `
    }
}

function load_default_css(element) {
    validator.insertAdjacentHTML("afterbegin", 
    `
        <link rel="stylesheet" type="text/css" href="stylsheet.css">
    `
}

function gen_css_loader() {
    let element = document.getElementById("css_load");
    //Check if browser supports local storage
    if (web_storage_supported()) {
        load_css_from_storage(element);
    } else {
        load_default_css(element);
    }
}
```

Only issue could be security I guess.

**Comment by jacekkopecky** [comment]
Where would you like your custom CSS to apply? I can see three options:
- restyle the whole ch@or – that's best handled by a GitHub pull request where you suggest a new CSS; or you could have your own stylesheet in a browser extension like [Stylish](https://userstyles.org/).
- restyle "your feed on ch@or" – we don't distinguish users yet so that would be some kind of "theme" support later
- restyle individual messages – that would be rich text support, outside the scope of what we can do in 3-4 lectures.

**Comment by ear1grey** [comment]
In order to keep the issues list manageable we'll close question issues after one week of inactivity.
